// 4 - Fetching Data From API/codeial-react/src/components/PostsList.js
import React from 'react';
import axios from 'axios';
import Post from './Post';


class PostsList extends React.Component{
    constructor(props){
        super(props);

        this.state = {
            posts: []
        }

        this.getPosts();
    }

    getPosts(){
        axios.get('http://localhost:8000/api/v1/posts').then((data) => {this.setState({posts: data.data.posts})});
    }


  render(){
    return (
        <div>
            <h1>Codeial Posts</h1>
            <ul>
                {
                    this.state.posts.map((post) => <Post post={post} key={post._id} ></Post>)
                }

            </ul>
        </div>
      );
  }
}

export default PostsList;

// 5 - Fetching Data _ Axios Again!/codeal-vue/src/components/PostsList.vue
<template>
  <div class="posts-list">
    <h1>Codeial Posts</h1>
    <ul>
        <li v-for="post in posts" :key="post._id" class="post-item">
            {{post.content}} --> {{post.user.name}}
        </li>

    </ul>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  name: "PostsList",
  data() {
      return {
          posts: []
      }
  },
  mounted() {
      axios.get('http://localhost:8000/api/v1/posts').then((data) => {this.posts = data.data.posts});
  }

};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped lang="scss">

</style>
